WITH DATES AS (
    SELECT
        DISTINCT order_date AS FULL_DATE
    FROM
        {{ref ('stg_orders')}}
)

SELECT 
    TO_NUMBER(TO_CHAR(FULL_DATE, 'YYYYMMDD')) AS DATE_KEY,
    FULL_DATE,
    YEAR(FULL_DATE) AS YEAR,
    QUARTER(FULL_DATE) AS QUARTER,
    MONTH(FULL_DATE) AS MONTH,
    MONTHNAME(FULL_DATE) AS MONTH_NAME,
    WEEK(FULL_DATE) AS WEEK,
    DAY(FULL_DATE) AS DAY

FROM
    DATES
